version: "3"
services:
  appserver:
    container_name: server
    hostname: localhost
    image: nachmiasx/basic-spring:aviv-002
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data1
    privileged: true
